baseURL = "https://project-hop.org/"
languageCode = "en-us"
title = "Hop"
relativeURLs = true
disablePathToLower = true
staticDir = ["static", "documentation"]
disableKinds = ["taxonomyTerm"]
enableRobotsTXT = true

[params]
    socialProfiles = ["https://twitter.com/the_hop_project"]
    organizationLogo = "/img/logo-light.svg"
    organizationDescription = "Hop"

[Author]
    name = "The Hop Team"

[[menu.main]]
    name = "Documentation"
    identifier = "docs"
    weight = 1

[[menu.main]]
    name = "Getting started"
    parent = "docs"
    weight = 1
    identifier = "getting-started"
    url = "/manual/latest/"

[[menu.main]]
    name = "Architecture"
    parent = "docs"
    weight = 2
    identifier = "docs-architecture"
    url = "/docs/architecture/"

[[menu.main]]
    name = "Roadmap"
    parent = "docs"
    weight = 3
    identifier = "docs-roadmap"
    url = "/docs/roadmap/"

[[menu.main]]
    name = "Q&A"
    parent = "docs"
    weight = 4
    identifier = "docs-qa"
    url = "/docs/qa"

[[menu.main]]
    name = "Community"
    identifier = "community"
    weight = 2

[[menu.main]]
    name = "Contributing"
    parent = "community"
    weight = 1
    identifier = "community-contributing"
    url = "/community/contributing/"

[[menu.main]]
    name = "Jira"
    parent = "community"
    weight = 2
    identifier = "community-jira"
    url = "https://jira.project-hop.org"

[[menu.main]]
    name = "Forum"
    parent = "community"
    weight = 3
    identifier = "community-forum"
    url = "https://forums.project-hop.org"

[[menu.main]]
    name = "Jenkins"
    parent = "community"
    weight = 4
    identifier = "community-jenkins"
    url = "https://jenkins.project-hop.org"

[[menu.main]]
    name = "Artifactory"
    parent = "community"
    weight = 5
    identifier = "community-artifactory"
    url = "https://artifactory.project-hop.org"

[[menu.main]]
    name = "Team"
    parent = "community"
    weight = 6
    identifier = "community-team"
    url = "/community/team/"

[[menu.main]]
    name = "Download"
    weight = 3
    identifier = "download"
    url = "/download/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 4

[[menu.main]]
    name = "License"
    parent = "about"
    weight = 1
    identifier = "about-license"
    url = "https://www.apache.org/licenses/LICENSE-2.0"


[module]

  [[module.mounts]]
    source = "documentation/_/data"
    target = "data"
